# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdbt2',
                'doc_host': 'https://butchland.github.io',
                'git_url': 'https://github.com/butchland/nbdbt2',
                'lib_path': 'nbdbt2'},
  'syms': {'nbdbt2.core': {'nbdbt2.core.foo': ('core.html#foo', 'nbdbt2/core.py')}}}
