test_dbt:
  outputs:
    dev:
      type: duckdb
      path: /home/butch2/play/experiments/nbtools/nbdbt2/test_dbt/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
