name: test_dbt_project2
version: '1.0'
profile: test_dbt_project2
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
log-path: logs
packages-install-path: dbt_packages
clean-targets:
- target
- dbt_packages
- logs
models:
  test_dbt_project2:
    +materialized: table
    # raw:
    #   +materialized: table
    # prep:
    #   +materialized: table
    # conformed:
    #   +materialized: view
vars:
  scenarios: 10000            # set number of scenarios. 100k is safe on 8GB of RAM
  include_actuals: true       # set to true to use actual game results, otherwise sim entire season
  latest_ratings: true        # set to true to use latest ELO ratings, otherwise use start of season ratings
  enable_export: false        # set to true to export files to parquet
  sim_start_game_id: 0        # placeholder one multi-container is in place
on-run-end: "{{ export_to_parquet( var('enable_export') ) }}" 
